version: '3'

services:
    # PHP service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bookmark-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - bookmark-network
        depends_on:
            - db
            - redis

    # Nginx service
    web:
        image: nginx:alpine
        container_name: bookmark-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - bookmark-network
        depends_on:
            - app

    # Database service
    db:
        image: mysql:8.0
        container_name: bookmark-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        volumes:
            - bookmark-data:/var/lib/mysql
        networks:
            - bookmark-network

    # Redis service (for queue)
    redis:
        image: redis:alpine
        container_name: bookmark-redis
        restart: unless-stopped
        networks:
            - bookmark-network

    # Queue worker
    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bookmark-queue
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan queue:work redis --sleep=3 --tries=3 --timeout=90
        volumes:
            - ./:/var/www
        networks:
            - bookmark-network
        depends_on:
            - app
            - redis

networks:
    bookmark-network:
        driver: bridge

volumes:
    bookmark-data:
        driver: local
